In [41]:
# 1. Create a null vector of size 10 but the fifth value which is 1 
# 2. Create a vector with values ranging from 10 to 49
# 3. Reverse a vector
# 4. Create a 3x3 matrix with values ranging from 0 to 8
# 5. Find indices of non-zero elements from [1,2,0,0,4,0]
# 6. Create a 3x3x3 array with random values
# 7. Create a 10x10 array with random values and find the minimum and maximum values
# 8. Create a 2d array with 1 on the border and 0 inside


In [2]:
import numpy as np

In [52]:
# 1. Create a null vector of size 10 but the fifth value which is 1 
null_arr = np.zeros(10)
null_arr[4] = 1
null_arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [55]:
# 2 Create a vector with values ranging from 10 to 49
arr2 = np.arange(10,50,1)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [56]:
# 3. Reverse a vector
arr2 = np.arange(10,50,1)
arr2[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [57]:
# 4. Create a 3x3 matrix with values ranging from 0 to 8
np.array(np.arange(0,9,1)).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
# 5. Find indices of non-zero elements from [1,2,0,0,4,0]
arr = np.array([1,2,0,0,4,0])
non_0 = arr!=0

np.where(non_0)

(array([0, 1, 4]),)

In [59]:
# 6. Create a 3x3x3 array with random values
np.random.rand(3, 3, 3)


array([[[0.61036621, 0.2468609 , 0.83719101],
        [0.89056948, 0.97274269, 0.3106291 ],
        [0.2558682 , 0.11871803, 0.12990107]],

       [[0.78887663, 0.18298661, 0.67037064],
        [0.99133401, 0.37049793, 0.64297582],
        [0.72160716, 0.89108098, 0.26160319]],

       [[0.42053243, 0.93112563, 0.61328388],
        [0.97602796, 0.92150131, 0.16297118],
        [0.97382572, 0.68551762, 0.56773325]]])

In [60]:
# 7. Create a 10x10 array with random values and find the minimum and maximum values
arr7 = np.random.randint(1000, size=(100)).reshape(10,10)
arr7.min(),arr7.max()

(5, 991)

In [61]:
# 8. Create a 2d array with 1 on the border and 0 inside
arr_8 = np.ones((10, 10))
arr_8[1:-1, 1:-1] = 0
arr_8

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])