In [13]:
import pandas as pd 
import numpy as np

In [53]:
#Series
#Creating series using a list

ps = pd.Series([1, 2, 3])
print(ps,"\n")
print(ps*100+10,"\n")

0    1
1    2
2    3
dtype: int64 

0    110
1    210
2    310
dtype: int64 



In [52]:
np.array([1, 2, 3])

array([10, 20, 30])

In [4]:
#Viewing series as an array
ps.values

array([1, 2, 3])

In [55]:
#labeling your series as per your own choice. you dont have this liberty in numpy
my_first_series = pd.Series([1, 2, 3], index = ['A', 'B', 'C'])
my_first_series

A    1
B    2
C    3
dtype: int64

In [6]:
my_first_series.index

Index(['A', 'B', 'C'], dtype='object')

In [7]:
#use index to access its value
my_first_series['A']

1

In [59]:
#manipulating the value of a series through an index
my_first_series['A'] = 100
my_first_series

A    100
B      2
C      3
dtype: int64

In [60]:
#Accessing subeset of series using indices
my_first_series[['A', 'C']]

A    100
C      3
dtype: int64

In [62]:
#filtering series using a condition
my_first_series[my_first_series > 5]

A    100
dtype: int64

In [63]:
my_first_series[my_first_series < 5]

B    2
C    3
dtype: int64

In [64]:
#Create a Series

my_first_series = pd.Series(np.arange(10))
my_first_series

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [13]:
#creating a series using a tuple
my_first_series = pd.Series((1, 2, 3, 4, 5, 6))
my_first_series

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [70]:
 pd.Series((1, 2, 3, 4, 5, 6),(11, 12, 13, 14, 15, 16))

11    1
12    2
13    3
14    4
15    5
16    6
dtype: int64

In [14]:
#creating a series using a dictionary. Keys are inferred as indices. 
my_first_series = pd.Series({'John' : 34, 'Jim' : 30, 'Sara' : 26, 'Anil' : 40, 'Majid' : 38})
my_first_series

John     34
Jim      30
Sara     26
Anil     40
Majid    38
dtype: int64

In [15]:
my_first_series.John

34

In [16]:
my_first_series['Majid']

38

In [17]:
#DataFrame
#Create a dataframe using a dictionary

data = {"Name" : ['Ohio', 'Ontario', 'London', 'Paris', 'Melbourne', 'Delhi', 'Beijing'],
        "year" : [2020, 2023, 2019, 2018, 2010, 1999, 1996],
        "cases" :[34, 12, 50, 30, 49, 190, 80]}
data

{'Name': ['Ohio',
  'Ontario',
  'London',
  'Paris',
  'Melbourne',
  'Delhi',
  'Beijing'],
 'year': [2020, 2023, 2019, 2018, 2010, 1999, 1996],
 'cases': [34, 12, 50, 30, 49, 190, 80]}

In [18]:
#A 2-d data structure labeled at both the dimensions. 
my_first_dataframe = pd.DataFrame(data, index = ['A', 'B', 'C', 'D', 'E', 'F', 'G'])
my_first_dataframe

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
D      Paris  2018     30
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [19]:
#just see top 5 values
my_first_dataframe.head()

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
D      Paris  2018     30
E  Melbourne  2010     49

In [20]:
#just display bottom fove values
my_first_dataframe.tail()

Name  year  cases
C     London  2019     50
D      Paris  2018     30
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [76]:
#dataframe in a certain order
df = pd.DataFrame(data, columns = ['year', 'Name', 'cases'])
df.columns = ['new_year', 'new_name', 'new_cases']
# df[[ 'new_name','new_year', 'new_cases']]
df

new_year   new_name  new_cases
0      2020       Ohio         34
1      2023    Ontario         12
2      2019     London         50
3      2018      Paris         30
4      2010  Melbourne         49
5      1999      Delhi        190
6      1996    Beijing         80

In [22]:
#access a column
my_first_dataframe['Name']

A         Ohio
B      Ontario
C       London
D        Paris
E    Melbourne
F        Delhi
G      Beijing
Name: Name, dtype: object

In [23]:
#access a row by the name of the index
my_first_dataframe.loc['G']

Name     Beijing
year        1996
cases         80
Name: G, dtype: object

In [24]:
my_first_dataframe

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
D      Paris  2018     30
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [25]:
#Accessing a particular element requires selecting a column and the index
my_first_dataframe['Name']['D']

'Paris'

In [26]:
#Replacing a particular value in dataframe
my_first_dataframe['Name']['D'] = 'Durham'
my_first_dataframe

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
D     Durham  2018     30
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [27]:
#Delete or drop a row or a column

my_first_dataframe

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
D     Durham  2018     30
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [28]:
#Lets say want to drop 4th index

my_first_dataframe.drop('D')

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [29]:
my_first_dataframe

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
D     Durham  2018     30
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [30]:
#The drop method just temporarily drops and shows you a view of it. In actual its not dropped

my_first_dataframe.drop('D', inplace = True)

In [31]:
my_first_dataframe

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [32]:
#what if you want to drop a column

my_first_dataframe.drop('year', axis = 1)

Name  cases
A       Ohio     34
B    Ontario     12
C     London     50
E  Melbourne     49
F      Delhi    190
G    Beijing     80

In [33]:
my_first_dataframe

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [34]:
#Access via filtering over a condition on one column
my_first_dataframe[my_first_dataframe['cases'] < 50]

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
E  Melbourne  2010     49

In [35]:
my_first_dataframe[my_first_dataframe['year'] > 2015]

Name  year  cases
A     Ohio  2020     34
B  Ontario  2023     12
C   London  2019     50

In [36]:
#Accessing using multiple conditions
my_first_dataframe[((my_first_dataframe['year'] > 2015) & (my_first_dataframe['cases'] > 30))]

Name  year  cases
A    Ohio  2020     34
C  London  2019     50

In [37]:
#Sorting

my_first_dataframe

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [38]:
my_new_dataframe = my_first_dataframe.set_index('year')
my_new_dataframe

Name  cases
year                  
2020       Ohio     34
2023    Ontario     12
2019     London     50
2010  Melbourne     49
1999      Delhi    190
1996    Beijing     80

In [39]:
my_new_dataframe.sort_index(ascending=True)

Name  cases
year                  
1996    Beijing     80
1999      Delhi    190
2010  Melbourne     49
2019     London     50
2020       Ohio     34
2023    Ontario     12

In [40]:
my_first_dataframe

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [41]:
#Sorting without setting an index
my_first_dataframe.sort_values('year')

Name  year  cases
G    Beijing  1996     80
F      Delhi  1999    190
E  Melbourne  2010     49
C     London  2019     50
A       Ohio  2020     34
B    Ontario  2023     12

In [42]:
my_first_dataframe.sort_values(['Name','year'])

Name  year  cases
G    Beijing  1996     80
F      Delhi  1999    190
C     London  2019     50
E  Melbourne  2010     49
A       Ohio  2020     34
B    Ontario  2023     12

In [43]:
my_first_dataframe

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [44]:
my_first_dataframe[['cases']].sum()

cases    415
dtype: int64

In [45]:
my_first_dataframe[['cases']].mean()

cases    69.166667
dtype: float64

In [46]:
np.random.randint(5, size = (7))

array([3, 1, 4, 4, 1, 4, 2])

In [47]:
#Add a column to an existing dataframe
my_first_dataframe['group'] = np.random.randint(5, size = (6))
my_first_dataframe

Name  year  cases  group
A       Ohio  2020     34      0
B    Ontario  2023     12      2
C     London  2019     50      4
E  Melbourne  2010     49      4
F      Delhi  1999    190      0
G    Beijing  1996     80      1

In [48]:
#unique values in a column
my_first_dataframe['group'].unique()

array([0, 2, 4, 1])

In [49]:
#frequency of the column
my_first_dataframe['group'].value_counts()

4    2
0    2
2    1
1    1
Name: group, dtype: int64

Create a dataframe from a dictionary where the keys are the names of countries, the values are the gdp and indices are last 10 years. 
Now try to find the average gdp combined for all countries over past 10 years. 

In [25]:

data_ ={
    "Years":np.arange(2014,2024),
    "India":np.random.randint(100,150,size=10),
    "Candada":np.random.randint(100,150,size=10),
    "China":np.random.randint(100,150,size=10),
    "Bhutan":np.random.randint(100,150,size=10),
    "UK":np.random.randint(100,150,size=10),
}

df = pd.DataFrame(data_).set_index("Years")
display(df)
print(df.mean())

print("\nAll",df.mean().mean())

India  Candada  China  Bhutan   UK
Years                                    
2014     133      138    126     147  138
2015     144      142    123     112  103
2016     145      128    112     139  100
2017     108      137    123     118  130
2018     100      140    142     101  108
2019     107      149    125     129  141
2020     131      118    114     129  120
2021     126      136    103     104  111
2022     103      113    122     114  113
2023     139      139    118     126  139

India      123.6
Candada    134.0
China      120.8
Bhutan     121.9
UK         120.3
dtype: float64

All 124.12


11